title: Computer Vision for Drug Discovery Where Are We and What is Beyond?
description: Spatial Transcriptomics, Cell Painting, Optical Pooled Screening, image-based biomarkers, and other image modalities with Computer Vision and AI techniques for modern Drug Discovery
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
